from .about_route import about
from .auth_route import auth
from .contact_route import contact
from .cover_route import cover
from .education_route import education
from .project_route import project
from .resume_route import resume
from .skill_route import skill
from .user_route import user